version: '3.7'

services:
  app:
    build:
      context: ./docker
      dockerfile: dev.Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ~/.gitconfig:/etc/.gitconfig
    user: '1000'
    command: bash -c "yarn && yarn serve"
    ports:
      - 3000:8080
